### ISSUE TITLE
Disable Python virtualenv

### ISSUE THREAD

**Issue by Sbozzolo** [pure-fish/pure#274]
Is it possible to disable the feature that adds the Python virtualenv?

I tried looking for this flag, but couldn't find it, so I guess it is not available. In that case, I think it would be nice to have.

**Comment by edouard-lopez** [comment]
@Sbozzolo no there is no flag for it, we use the environment variable `VIRTUAL_ENV` or `CONDA_DEFAULT_ENV` to trigger it. 

A temporary solution would be to redefine `_pure_prefix_root_prompt` as an empty function in `~/.config/fish/functions/_pure_prefix_root_prompt.fish`:

	function _pure_prefix_root_prompt
	end

A better solution would be to had a feature flag and submit a PR :hugs: 
For help, you can have a look at `_pure_prefix_root_prompt` feature or ask here:
* [test file](https://github.com/pure-fish/pure/blob/master/tests/_pure_prefix_root_prompt.test.fish)
* [function file](https://github.com/pure-fish/pure/blob/master/functions/_pure_prefix_root_prompt.fish)

**Comment by officerats** [comment]
It also kinda ruins prompt line formatting for me.

My set up on version 3.5.0 is as follows:

```
set --universal pure_enable_single_line_prompt true
set --universal pure_show_prefix_root_prompt true
set --universal pure_begin_prompt_with_current_directory false
set --universal pure_threshold_command_duration 60
```
and my prompt looks like

`~test  ❯`

instead of expected

`~ test ❯`


Note there's 
- a space missing after current dir
- double space between conda env name and pure symbol prompt, which can't been seen here because of Markdown formatting, but it's there

My random guess about double space is it happens because there's explicit `$space` after `$virtualenv \` in [_pure_prompt
](https://github.com/pure-fish/pure/blob/081f81cd6c32a44f92c0c98cc93d64d035f5dddd/functions/_pure_prompt.fish#L23). I don't really get why there's missing space between current dir and conda env name though. My guess might be wrong though.

**Comment by edouard-lopez** [comment]
@officerats could you open an issue about the spacing as it's unrelated to the original issue?
